DROP TABLE EADV;
/
CREATE TABLE EADV
(
    eid NUMBER(12,0) NOT NULL,
    att VARCHAR2(32) NOT NULL,
    dt DATE NOT NULL,
    val NUMBER(15,2)

);


CREATE BITMAP INDEX "TKC"."EADV_ATT_IDX" ON "TKC"."EADV" ("ATT");

CREATE BITMAP INDEX "TKC"."EADV_EID_IDX" ON "TKC"."EADV" ("EID");

DROP INDEX "TKC"."EADV_DT_IDX";


