DROP TABLE EADV;
CREATE TABLE EADV
(
    id INT NOT NULL,
    eid NUMBER(*,0) NOT NULL,
    att VARCHAR2(32) NOT NULL,
    dt DATE NOT NULL,
    val NUMBER(*,0),
    CONSTRAINT EADV_PK PRIMARY KEY (id)
    --CONSTRAINT EADV_UC UNIQUE (eid,att,dt)
);

DROP SEQUENCE EADV_seq;
CREATE SEQUENCE EADV_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

DROP TRIGGER EADV_tg;
CREATE TRIGGER EADV_tg
BEFORE INSERT ON EADV
FOR EACH ROW
WHEN (new.id IS NULL)
BEGIN
   SELECT EADV_seq.NEXTVAL
   INTO   :new.id
   FROM   dual;
END;
 
 