CREATE TABLE "RMAN_LOC_MAP_TMP" 
   (	"LINKED_REGISTRATIONS_ID" NUMBER(*,0), 
	"DATE_RUN" DATE, 
	"LOC" NUMBER(1,0), 
	"LOC.CMI" NUMBER(1,0), 
	"LOC.CMI.UsualClinic" NVARCHAR2(1000), 
	"LOC.RECENT" NUMBER(1,0), 
	"LOC.RECENT.DATE" DATE, 
	"LOC.RECENT.HEALTH_CENTRE" NVARCHAR2(2000), 
	"LOC.RECENT.DOH_REGION" NVARCHAR2(4), 
	"LOC.RECENT.DOH_DISTRICT" NVARCHAR2(500), 
	"LOC.RECENT.SA2_NAME" NVARCHAR2(500), 
	"LOC.RECENT.MMR" NUMBER, 
	"LOC.RECENT.LATITUDE" NUMBER(9,6), 
	"LOC.RECENT.LONGITUDE" NUMBER(9,6), 
	"LOC.FRQ" NUMBER(1,0), 
	"LOC.FRQ.HEALTH_CENTRE" NVARCHAR2(2000), 
	"LOC.FRQ.DOH_REGION" NVARCHAR2(4), 
	"LOC.FRQ.DOH_DISTRICT" NVARCHAR2(500), 
	"LOC.FRQ.SA2_NAME" NVARCHAR2(500), 
	"LOC.FRQ.MMR" NUMBER, 
	"LOC.FRQ.LATITUDE" NUMBER, 
	"LOC.FRQ.LONGITUDE" NUMBER
   );
@"C:\Users\abeya\Documents\Oracle11g\tkc-data\loc_mapt.sql";

CREATE UNIQUE INDEX EID ON RMAN_LOC_MAP_TMP (LINKED_REGISTRATIONS_ID);

CREATE INDEX LOC ON RMAN_LOC_MAP_TMP ("LOC.CMI.UsualClinic");

select t1.*,t2."LOC.CMI.UsualClinic" 
from rout_pcd t1
inner join rman_loc_map_tmp t2 on t2."LINKED_REGISTRATIONS_ID"=t1.eid
where t2."LOC.CMI.UsualClinic"='Maningrida Community Health Centre';
