DROP TABLE SYSTEM_RULES_CODES;

CREATE TABLE SYSTEM_RULES_CODES
(
    SYSTEM_RULES_ATTRIBUTE_ID VARCHAR2(255),
    CLASSIFICATION_LIKE VARCHAR2(255),
    CODE_LIKE VARCHAR2(255)
);

REM INSERTING into SYSTEM_RULES_CODES
SET DEFINE OFF;
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.AKI.Dx.ICD','%ICD%','N17%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.AKI.Dx.ICPC','%ICPC%','U99005%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L00%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L01%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L02%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L03%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L04%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L05%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L06%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L07%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L08%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','L09%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICD','%ICD%','M86%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CTI.Dx.ICPC','%ICPC%','S76%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.CABG.Dx.ICD','%ICD%','Z95.1%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.CABG.Dx.ICPC','%ICPC%','K54007%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I20%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I21%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I22%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I23%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I24%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICD','%ICD%','I25%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICPC','%ICPC%','K74%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICPC','%ICPC%','K75%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CAD.Dx.ICPC','%ICPC%','K76%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CVA.Dx.ICD','%ICD%','G46%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CVA.Dx.ICPC','%ICPC%','K89%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CVA.Dx.ICPC','%ICPC%','K90%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.CVA.Dx.ICPC','%ICPC%','K91%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.Dx.ICPC','%ICPC%','K22%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.HTN.Dx.ICD','%ICD%','T89%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.HTN.Dx.ICPC','%ICPC%','K85%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.HTN.Dx.ICPC','%ICPC%','K86%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.HTN.Dx.ICPC','%ICPC%','K87%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.PVD.Dx.ICD','%ICD%','I70%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.PVD.Dx.ICD','%ICD%','I71%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.PVD.Dx.ICD','%ICD%','I72%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.PVD.Dx.ICD','%ICD%','I73%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.PVD.Dx.ICPC','%ICPC%','K92%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.CVD.VHD.Dx.ICPC','%ICPC%','K83%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICD','%ICD%','E08%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICD','%ICD%','E09%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICD','%ICD%','E10%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICD','%ICD%','E11%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICD','%ICD%','E14%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICPC','%ICPC%','T89%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.DM.Dx.ICPC','%ICPC%','T90%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.LIT.Dx.ICD','%ICD%','N20%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.LIT.Dx.ICPC','%ICPC%','U95%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.OBS.Dx.ICD','%ICD%','E66%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CD.OBS.Dx.ICPC','%ICPC%','T82%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICD','ICD','N18.%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99034');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99035');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99036');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99037');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99038');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99039');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99043');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('CKD.Dx.ICPC','%ICPC%','U99044');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('MANAGE.SENTINEL','%ICD%','N17%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('MANAGE.SENTINEL','%ICPC%','U99005%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HD.Dx.ICD','%ICD%','Z49.1%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HD.Dx.ICPC','%ICPC%','U59001%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HD.Dx.ICPC','%ICPC%','U59008%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HD.Px.Tertiary','CARESYS','13100-00%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HD.Px.Tertiary','CARESYS','13100-03%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.HHD.Dx.ICPC','%ICPC%','U59J99%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Dx.ICD','%ICD%','Z49.2%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Dx.ICPC','%ICPC%','U59007%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Dx.ICPC','%ICPC%','U59009%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Px.Tertiary','CARESYS','13100-06%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Px.Tertiary','CARESYS','13100-07%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.PD.Px.Tertiary','CARESYS','13100-08%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.TP.Dx.ICD','%ICD%','Z94%');
Insert into SYSTEM_RULES_CODES (SYSTEM_RULES_ATTRIBUTE_ID,CLASSIFICATION_LIKE,CODE_LIKE) values ('RRT.TP.Dx.ICPC','%ICPC%','U28001%');