DROP TABLE EADV2;
/
CREATE TABLE EADV2
(
    id INT NOT NULL,
    eid NUMBER(*,0) NOT NULL,
    att VARCHAR2(32) NOT NULL,
    dt DATE NOT NULL,
    val NUMBER(*,0),
    CONSTRAINT EADV2_PK PRIMARY KEY (id)
    --CONSTRAINT EADV_UC UNIQUE (eid,att,dt)
);
/
DROP SEQUENCE EADV2_seq;
CREATE SEQUENCE EADV2_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
/
DROP TRIGGER EADV2_tg;
CREATE TRIGGER EADV2_tg
BEFORE INSERT ON EADV2
FOR EACH ROW
WHEN (new.id IS NULL)
BEGIN
   SELECT EADV2_seq.NEXTVAL
   INTO   :new.id
   FROM   dual;
END;
/
CREATE INDEX att_idx2 ON EADV2(att);