WITH CTE000 AS (SELECT EID FROM EADV GROUP BY EID),CTE001 AS (SELECT EID,VAL,ROW_NUMBER() OVER(PARTITION BY EID,ATT ORDER BY EID,DT DESC) AS rank  FROM EADV WHERE ATT='eGFR'),
CTE002 AS (SELECT EID,VAL AS egfrl FROM CTE001 WHERE rank=1),
CTE003 AS (SELECT EID,VAL,ROW_NUMBER() OVER(PARTITION BY EID,ATT ORDER BY EID,DT DESC) AS rank  FROM EADV WHERE ATT='ACR'),
CTE004 AS (SELECT EID,VAL AS acrl FROM CTE003 WHERE rank=1)
 SELECT CTE000.EID, CTE002.egfrl 
,CTE004.acrl 
FROM CTE000 LEFT OUTER JOIN CTE002 ON CTE002.EID=CTE000.EID 
 LEFT OUTER JOIN CTE004 ON CTE004.EID=CTE000.EID 
;