from pathlib import Path

PICORULE_FILE_PATH = "picorules"

INSERT_SCRIPT_FILE_PATH = "tkc-rman-insert-ruleblocks_generated.sql"


ScriptHeaderClean = """
-----------------------------------------------------------------------
--                              WARNING                              --
-- This insert script is generated by running:                       --
--   python scripts/generate_insert_script.py                        --
-- do not modify it by hand, rather edit the *.prb files             --
-- and rerun the script                                              --
-----------------------------------------------------------------------


CLEAR SCREEN;
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

DECLARE
    rb          RMAN_RULEBLOCKS%ROWTYPE;
BEGIN

"""

BlockFmt = """
    -- BEGINNING OF RULEBLOCK --
    rb.blockid := '{blockid}';
    
    DELETE FROM rman_ruleblocks WHERE blockid=rb.blockid;
    
    rb.picoruleblock := '{body}';
    
    rb.picoruleblock := replace(rb.picoruleblock, '[[rb_id]]', rb.blockid);
    rb.picoruleblock := rman_pckg.sanitise_clob(rb.picoruleblock);
    INSERT INTO rman_ruleblocks (blockid, picoruleblock) VALUES (rb.blockid, rb.picoruleblock);
    COMMIT;
    -- END OF RULEBLOCK --

"""

ScriptFooterClean = """
END;

COMMIT;
"""



def processfiles():
    scriptlines = list()

    scriptlines = scriptlines + ScriptHeaderClean.splitlines()

    for path in sorted(Path(PICORULE_FILE_PATH).glob("*.prb")):
        rb_id = path.stem
        body = path.read_text()

        script_body = BlockFmt.format(blockid=rb_id, body = body)

        scriptlines = scriptlines + script_body.splitlines()

    scriptlines = scriptlines + ScriptFooterClean.splitlines()

    Path(INSERT_SCRIPT_FILE_PATH).write_text('\n'.join(scriptlines))


if __name__ == "__main__":
    processfiles()
